# Generated by Django 3.0.6 on 2020-05-22 04:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('valid_till', models.DateTimeField(db_index=True, null=True)),
            ],
            options={
                'db_table': 'all_keys',
            },
        ),
        migrations.CreateModel(
            name='AvailableKeys',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_on', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'available_keys',
            },
        ),
        migrations.CreateModel(
            name='UsedKeys',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valid_till', models.DateTimeField(db_index=True, null=True)),
            ],
            options={
                'db_table': 'used_keys',
            },
        ),
    ]
